=== HendriXML/KiCad-BOM-reporter/XmlSchemas.Common.KiCadBOMReporter/ComponentMapping.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Devices">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Library" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="Part">
                <xs:complexType>
                  <xs:attribute name="Part" type="xs:string" use="required" />
                  <xs:attribute name="Component" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string" use="required" />
            <xs:attribute name="Component" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== HendriXML/KiCad-BOM-reporter/Resources.Project.ComponentMappings/Generic.xml
<Devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XmlSchemas.Common.KiCadBOMReporter/ComponentMapping.xsd"> 
  <Library Name="Amplifier_Operational" Component="OpAmp">
  </Library>
  <Library Name="Connector_Generic" Component="Connector">
  </Library>
  <Library Name="Connector" Component="Connector">
  </Library>
  <Library Name="Jumper" Component="NonComponent">
  </Library>
  <Library Name="Comparator" Component="Comparator">
  </Library>
  <Library Name="Diode">
    <Part Part="1N5817" Component="SchottkyDiode"/>
    <Part Part="1N5818" Component="SchottkyDiode"/>
    <Part Part="1N5819" Component="SchottkyDiode"/>
    <Part Part="1N4001" Component="Diode"/>
    <Part Part="1N4002" Component="Diode"/>
    <Part Part="1N4003" Component="Diode"/>
    <Part Part="1N4004" Component="Diode"/>
    <Part Part="1N4005" Component="Diode"/>
    <Part Part="1N4006" Component="Diode"/>
    <Part Part="1N4007" Component="Diode"/>
  </Library>
  <Library Name="Transistor_BJT">
    <Part Part="2N3906" Component="PNPTransistor"/>
    <Part Part="2N3904" Component="NPNTransistor"/>
    <Part Part="TIP125" Component="PNPTransistor"/>
  </Library>
  <Library Name="Transistor_FET">
    <Part Part="2N7000" Component="NMOSFET"/>
    <Part Part="IRLZ44N" Component="NMOSFET"/>
  </Library>
</Devices>
