=== HendriXML/KiCad-BOM-reporter/XmlSchemas.Common.KiCadBOMReporter/ComponentKinds.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Document">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="ComponentKind">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Language">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Name">
                      <xs:complexType>
                        <xs:attribute name="Text" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Header">
                      <xs:complexType>
                        <xs:attribute name="Text" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="LangID" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== HendriXML/KiCad-BOM-reporter/Resources.Project.CodeGen/ComponentKinds.xml
<?xml version="1.0" encoding="utf-8"?>
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XmlSchemas.Common.KiCadBOMReporter/ComponentKinds.xsd">
  <ComponentKind Name="None">
    <Language LangID="en-GB">
      <Name Text=""/>
      <Header Text=""/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text=""/>
      <Header Text=""/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="Resistor">
    <Language LangID="en-GB">
      <Name Text="resistor"/>
      <Header Text="Resistors"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="weerstand"/>
      <Header Text="Weerstanden"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="VariableResistor">
    <Language LangID="en-GB">
      <Name Text="variable resistor"/>
      <Header Text="Variable resistors"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="variabele weerstand"/>
      <Header Text="Variabele weerstanden"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="Capacitor">
    <Language LangID="en-GB">
      <Name Text="capacitor"/>
      <Header Text="Capacitors"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="condensator"/>
      <Header Text="Condensatoren"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="PolarisedCapacitor">
    <Language LangID="en-GB">
      <Name Text="polarised capacitor"/>
      <Header Text="Polarised capacitors"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="gepolariseerde condensator"/>
      <Header Text="Gepolariseerde condensatoren"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="VariableCapacitor">
    <Language LangID="en-GB">
      <Name Text="variable capacitor"/>
      <Header Text="Variable capacitors"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="variable condensator"/>
      <Header Text="Variable condensatoren"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="Inductor">
    <Language LangID="en-GB">
      <Name Text="inductor"/>
      <Header Text="Inductors"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="spoel"/>
      <Header Text="Spoelen"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="BridgeRectifier">
    <Language LangID="en-GB">
      <Name Text="bridge rectifier"/>
      <Header Text="Bridge rectifiers"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="gelijkrichter"/>
      <Header Text="Gelijkrichters"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="ZenerDiode">
    <Language LangID="en-GB">
      <Name Text="zener diode"/>
      <Header Text="Zener diodes"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="zenerdiode"/>
      <Header Text="Zenerdiodes"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="Diode">
    <Language LangID="en-GB">
      <Name Text="diode"/>
      <Header Text="Diodes"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="diode"/>
      <Header Text="Diodes"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="SchottkyDiode">
    <Language LangID="en-GB">
      <Name Text="schottky diode"/>
      <Header Text="Schottky diodes"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="schottkydiode"/>
      <Header Text="Schottkydiodes"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="Laserdiode">
    <Language LangID="en-GB">
      <Name Text="laser diode"/>
      <Header Text="Laser diodes"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="laserdiode"/>
      <Header Text="Laserdiodes"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="Photodiode">
    <Language LangID="en-GB">
      <Name Text="photodiode"/>
      <Header Text="Photodiodes"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="photodiode"/>
      <Header Text="Photodiodes"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="SpecialDiode">
    <Language LangID="en-GB">
      <Name Text="special diode"/>
      <Header Text="Special diodes"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="speciale diode"/>
      <Header Text="Speciale diodes"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="DualDiode">
    <Language LangID="en-GB">
      <Name Text="dual diode"/>
      <Header Text="Dual diodes"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="dual diode"/>
      <Header Text="Dual diodes"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="NPNTransistor">
    <Language LangID="en-GB">
      <Name Text="npn transistor"/>
      <Header Text="NPN transistors"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="npn transistor"/>
      <Header Text="NPN transistors"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="PNPTransistor">
    <Language LangID="en-GB">
      <Name Text="pnp transistor"/>
      <Header Text="PNP transistors"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="pnp transistor"/>
      <Header Text="PNP transistors"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="NFET">
    <Language LangID="en-GB">
      <Name Text="n-fet"/>
      <Header Text="NFETs"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="n-fet"/>
      <Header Text="N-FET's"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="PFET">
    <Language LangID="en-GB">
      <Name Text="p-fet"/>
      <Header Text="P-FETs"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="p-fet"/>
      <Header Text="P-FET's"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="NIGBT">
    <Language LangID="en-GB">
      <Name Text="n-igbt"/>
      <Header Text="N-IGBTs"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="n-igbt"/>
      <Header Text="N-IGBT's"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="NJFET">
    <Language LangID="en-GB">
      <Name Text="njfet"/>
      <Header Text="N-JFETs"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="njfet"/>
      <Header Text="N-JFET's"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="PJFET">
    <Language LangID="en-GB">
      <Name Text="p-jfet"/>
      <Header Text="P-JFETs"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="p-jfet"/>
      <Header Text="P-JFET's"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="NMOSFET">
    <Language LangID="en-GB">
      <Name Text="n-mosfet"/>
      <Header Text="N-MOSFETs"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="n-mosfet"/>
      <Header Text="N-MOSFET's"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="PMOSFET">
    <Language LangID="en-GB">
      <Name Text="pmosfet"/>
      <Header Text="PMOSFETs"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="pmosfet"/>
      <Header Text="P-MOSFET's"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="PUJT">
    <Language LangID="en-GB">
      <Name Text="pujt"/>
      <Header Text="PUJTs"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="pujt"/>
      <Header Text="P-UJT's"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="NUJT">
    <Language LangID="en-GB">
      <Name Text="nujt"/>
      <Header Text="N-UJT's"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="nujt"/>
      <Header Text="N-UJT's"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="OpAmp" IsIntegratedCircuit="true">
    <Language LangID="en-GB">
      <Name Text="op amp"/>
      <Header Text="Op amps"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="opamp"/>
      <Header Text="Opamps"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="Comparator" IsIntegratedCircuit="true">
    <Language LangID="en-GB">
      <Name Text="comparator"/>
      <Header Text="Comparators"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="comparator"/>
      <Header Text="Comparators"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="Diac">
    <Language LangID="en-GB">
      <Name Text="diac"/>
      <Header Text="Diacs"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="diac"/>
      <Header Text="Diac's"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="SCR">
    <Language LangID="en-GB">
      <Name Text="scr"/>
      <Header Text="SCRs"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="scr"/>
      <Header Text="SCR's"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="TRIAC">
    <Language LangID="en-GB">
      <Name Text="triac"/>
      <Header Text="TRIACs"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="triac"/>
      <Header Text="TRIAC's"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="LED">
    <Language LangID="en-GB">
      <Name Text="led"/>
      <Header Text="LEDs"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="led"/>
      <Header Text="LED's"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="Fuse">
    <Language LangID="en-GB">
      <Name Text="fuse"/>
      <Header Text="Fuses"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="zekering"/>
      <Header Text="Zekeringen"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="Polyfuse">
    <Language LangID="en-GB">
      <Name Text="polyfuse"/>
      <Header Text="Polyfuses"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="Terugstelbare zekering"/>
      <Header Text="Terugstelbare zekeringen"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="Antenna">
    <Language LangID="en-GB">
      <Name Text="antenna"/>
      <Header Text="Antennas"/>
    </Language>
    <Language LangID="nl-NL">
      <Name Text="antenne"/>
      <Header Text="Antennes"/>
    </Language>
  </ComponentKind>
  <ComponentKind Name="Crystal">
    <Language LangID="en-GB">
      <Name Text="crystal"/>
      <Header Text="Crystals"/>
